title:            "@ssdr"
url:              http://ssdr.github.io
permalink:        pretty
highlighter:      pygments
markdown:         kramdown
google_analytics: UA-21332781-7
timezone:         Asia/Shanghai
gems:
  - jemoji
  - jekyll-mentions
